export const types = {
    GET_AUTOCOMPLETE_RESULT: 'GET_AUTOCOMPLETE_RESULT',
    GET_PLACES_REGION: 'GET_PLACES_REGION',
    CLEAR_AUTOCOMPLETE_RESULT: 'CLEAR_AUTOCOMPLETE_RESULT',
    GET_RECENT_SEARCHES: 'GET_RECENT_SEARCHES'
}